options:
  logging: CLOUD_LOGGING_ONLY

steps:
- id: 'Print ENV'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - -c
    - |
      echo "--- ENVIRONMENT VARIABLES ---"
      env
      echo "--- HOME is: $HOME ---"
      echo "--- Working Directory: $(pwd) ---"

- id: 'Fetch Service Account Key'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - -c
    - |
      echo "Saving key to $HOME/service-account-key.json"
      gcloud secrets versions access latest --secret=service-account-key-dev > $HOME/service-account-key.json

- id: 'Init OpenTofu'
  name: 'hashicorp/terraform:latest'
  dir: 'tofu'
  entrypoint: 'sh'
  args:
    - -c
    - |
      echo "Starting Terraform Init in $(pwd)"
      terraform init -backend-config="bucket=your-state-bucket" \
                     -backend-config="prefix=terraform/state/dev"

- id: 'Apply OpenTofu'
  name: 'hashicorp/terraform:latest'
  dir: 'tofu'
  entrypoint: 'sh'
  args:
    - -c
    - |
      echo "Starting Terraform Apply in $(pwd)"
      terraform apply -var-file=../environments/dev/terraform.tfvars \
                      -var="credentials=$HOME/service-account-key.json" \
                      -auto-approve
