substitutions:
  _ENVIRONMENT: 'dev'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- id: 'Fetch Service Account Key'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud config set project "prefab-bedrock-459220-u6"
    gcloud secrets versions access latest --secret=service-account-key-${_ENVIRONMENT} > $HOME/service-account-key.json

- id: 'Init OpenTofu'
  name: 'hashicorp/terraform:latest'
  dir: 'tofu'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init -backend-config="bucket=your-state-bucket" \
                   -backend-config="prefix=terraform/state/${_ENVIRONMENT}"

- id: 'Apply OpenTofu'
  name: 'hashicorp/terraform:latest'
  dir: 'tofu'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform apply -var-file=../environments/${_ENVIRONMENT}/terraform.tfvars \
                    -var="credentials=$HOME/service-account-key.json" \
                    -auto-approve
